before_script:
- cp ./config/database.example.yml ./config/database.yml
- rake db:setup RAILS_ENV=test
deploy:
  provider: heroku
  api_key:
    secure: QlvKpHuuiMwIIqMfpzDdSQlmGcd4LFh+6whqcYqE/O0nLgxynR/eJX0M4tVYWhvqTrGjDQjcaRjaHsEAJ3jqOnBCQHAdGHTrneC4twsOACxQLIwaRkUZjQww497ZxMsBGSLZ3wwwjB6kGKwgAvcdnd2ALM2EvMT+aLZiCZSRtZI=
  app: test-weblog
  on:
    repo: dmsilaev/weblog
